// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package recipesdb

import (
	"github.com/google/uuid"
)

type Ingredient struct {
	ItemID   uuid.UUID
	RecipeID uuid.UUID
	Quantity int64
}

type Recipe struct {
	ID     uuid.UUID
	UserID string
	Name   string
}
