// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/google/uuid"
)

type Ingredient struct {
	ItemID   uuid.UUID
	RecipeID uuid.UUID
	Quantity int64
}

type Item struct {
	ID     uuid.UUID
	Name   string
	UserID string
	ShopID uuid.UUID
}

type List struct {
	ID          uuid.UUID
	UserID      string
	CreatedDate int64
	Bought      string
}

type ListItem struct {
	ItemID   uuid.UUID
	ListID   uuid.UUID
	Quantity int64
}

type ListRecipe struct {
	RecipeID uuid.UUID
	ListID   uuid.UUID
	Quantity int64
}

type Recipe struct {
	ID     uuid.UUID
	UserID string
	Name   string
}

type Shop struct {
	ID     uuid.UUID
	UserID string
	Name   string
}

type User struct {
	ID string
}
